// ~50 exercícios comuns, agrupados por grupo muscular. videoUrl fica vazio (placeholder) —
// admin preenche com o vídeo real (YouTube não listado) via painel (Fase 5/8).
export const exercises = [
  // Peito
  { name: "Supino reto com barra", muscleGroup: "Peito" },
  { name: "Supino inclinado com halteres", muscleGroup: "Peito" },
  { name: "Crucifixo reto com halteres", muscleGroup: "Peito" },
  { name: "Crossover no cabo", muscleGroup: "Peito" },
  { name: "Flexão de braço", muscleGroup: "Peito" },
  { name: "Peck deck (voador)", muscleGroup: "Peito" },
  // Costas
  { name: "Puxada frontal (pulley)", muscleGroup: "Costas" },
  { name: "Remada curvada com barra", muscleGroup: "Costas" },
  { name: "Remada baixa (cabo)", muscleGroup: "Costas" },
  { name: "Remada unilateral com halter", muscleGroup: "Costas" },
  { name: "Barra fixa (pull-up)", muscleGroup: "Costas" },
  { name: "Pulldown com corda", muscleGroup: "Costas" },
  { name: "Levantamento terra", muscleGroup: "Costas" },
  // Ombro
  { name: "Desenvolvimento com halteres", muscleGroup: "Ombro" },
  { name: "Desenvolvimento militar com barra", muscleGroup: "Ombro" },
  { name: "Elevação lateral", muscleGroup: "Ombro" },
  { name: "Elevação frontal", muscleGroup: "Ombro" },
  { name: "Crucifixo inverso (posterior)", muscleGroup: "Ombro" },
  { name: "Encolhimento de trapézio", muscleGroup: "Ombro" },
  // Bíceps
  { name: "Rosca direta com barra", muscleGroup: "Bíceps" },
  { name: "Rosca alternada com halteres", muscleGroup: "Bíceps" },
  { name: "Rosca martelo", muscleGroup: "Bíceps" },
  { name: "Rosca scott", muscleGroup: "Bíceps" },
  { name: "Rosca no cabo", muscleGroup: "Bíceps" },
  // Tríceps
  { name: "Tríceps testa com barra", muscleGroup: "Tríceps" },
  { name: "Tríceps corda no cabo", muscleGroup: "Tríceps" },
  { name: "Tríceps francês com halter", muscleGroup: "Tríceps" },
  { name: "Mergulho em banco (dips)", muscleGroup: "Tríceps" },
  { name: "Tríceps coice com halter", muscleGroup: "Tríceps" },
  // Pernas
  { name: "Agachamento livre com barra", muscleGroup: "Pernas" },
  { name: "Leg press 45°", muscleGroup: "Pernas" },
  { name: "Cadeira extensora", muscleGroup: "Pernas" },
  { name: "Mesa flexora", muscleGroup: "Pernas" },
  { name: "Cadeira flexora", muscleGroup: "Pernas" },
  { name: "Afundo (passada)", muscleGroup: "Pernas" },
  { name: "Agachamento búlgaro", muscleGroup: "Pernas" },
  { name: "Stiff com barra", muscleGroup: "Pernas" },
  { name: "Elevação pélvica (hip thrust)", muscleGroup: "Pernas" },
  { name: "Panturrilha em pé", muscleGroup: "Pernas" },
  { name: "Panturrilha sentado", muscleGroup: "Pernas" },
  { name: "Cadeira adutora", muscleGroup: "Pernas" },
  { name: "Cadeira abdutora", muscleGroup: "Pernas" },
  // Core / Abdômen
  { name: "Abdominal supra", muscleGroup: "Abdômen" },
  { name: "Abdominal infra (elevação de pernas)", muscleGroup: "Abdômen" },
  { name: "Prancha isométrica", muscleGroup: "Abdômen" },
  { name: "Prancha lateral", muscleGroup: "Abdômen" },
  { name: "Abdominal oblíquo (bicicleta)", muscleGroup: "Abdômen" },
  { name: "Rollout com roda abdominal", muscleGroup: "Abdômen" },
  // Cardio / Funcional
  { name: "Corrida na esteira", muscleGroup: "Cardio" },
  { name: "Bicicleta ergométrica", muscleGroup: "Cardio" },
  { name: "Burpee", muscleGroup: "Funcional" },
  { name: "Corda naval (battle rope)", muscleGroup: "Funcional" },
  { name: "Polichinelo", muscleGroup: "Funcional" },
];
