// ~50 alimentos comuns na dieta brasileira — valores por 100 g (kcal/proteína/carboidrato/gordura),
// aproximados de tabelas nutricionais públicas (TACO/USDA). Placeholder editável no admin (Fase 5/8).
export const foods = [
  { name: "Arroz branco cozido", category: "Cereais", kcal: 128, protein: 2.5, carbs: 28, fat: 0.2 },
  { name: "Arroz integral cozido", category: "Cereais", kcal: 124, protein: 2.6, carbs: 25.8, fat: 1 },
  { name: "Feijão carioca cozido", category: "Leguminosas", kcal: 76, protein: 4.8, carbs: 13.6, fat: 0.5 },
  { name: "Feijão preto cozido", category: "Leguminosas", kcal: 77, protein: 4.5, carbs: 14, fat: 0.5 },
  { name: "Lentilha cozida", category: "Leguminosas", kcal: 93, protein: 6.3, carbs: 16.3, fat: 0.5 },
  { name: "Grão-de-bico cozido", category: "Leguminosas", kcal: 121, protein: 6.5, carbs: 20.2, fat: 1.9 },
  { name: "Peito de frango grelhado", category: "Carnes", kcal: 159, protein: 32, carbs: 0, fat: 3 },
  { name: "Coxa de frango assada", category: "Carnes", kcal: 195, protein: 26, carbs: 0, fat: 9.5 },
  { name: "Patinho moído cozido", category: "Carnes", kcal: 176, protein: 26.5, carbs: 0, fat: 7.3 },
  { name: "Carne bovina (alcatra) grelhada", category: "Carnes", kcal: 163, protein: 30, carbs: 0, fat: 4.5 },
  { name: "Tilápia grelhada", category: "Peixes", kcal: 128, protein: 26, carbs: 0, fat: 2.7 },
  { name: "Salmão grelhado", category: "Peixes", kcal: 208, protein: 22, carbs: 0, fat: 13 },
  { name: "Atum em água (lata)", category: "Peixes", kcal: 116, protein: 26, carbs: 0, fat: 1 },
  { name: "Ovo cozido", category: "Ovos", kcal: 155, protein: 13, carbs: 1.1, fat: 11 },
  { name: "Clara de ovo cozida", category: "Ovos", kcal: 52, protein: 11, carbs: 0.7, fat: 0.2 },
  { name: "Batata inglesa cozida", category: "Tubérculos", kcal: 87, protein: 1.9, carbs: 20.1, fat: 0.1 },
  { name: "Batata-doce cozida", category: "Tubérculos", kcal: 92, protein: 1.6, carbs: 21.5, fat: 0.1 },
  { name: "Mandioca cozida", category: "Tubérculos", kcal: 125, protein: 0.6, carbs: 30, fat: 0.3 },
  { name: "Inhame cozido", category: "Tubérculos", kcal: 97, protein: 2, carbs: 23, fat: 0.2 },
  { name: "Aveia em flocos", category: "Cereais", kcal: 394, protein: 14, carbs: 67, fat: 8 },
  { name: "Pão francês", category: "Pães", kcal: 300, protein: 8, carbs: 58, fat: 3 },
  { name: "Pão integral", category: "Pães", kcal: 253, protein: 9, carbs: 43, fat: 4 },
  { name: "Tapioca (goma)", category: "Cereais", kcal: 240, protein: 0.6, carbs: 59, fat: 0.1 },
  { name: "Macarrão cozido", category: "Cereais", kcal: 158, protein: 5.8, carbs: 31, fat: 0.9 },
  { name: "Quinoa cozida", category: "Cereais", kcal: 120, protein: 4.4, carbs: 21.3, fat: 1.9 },
  { name: "Banana prata", category: "Frutas", kcal: 98, protein: 1.3, carbs: 26, fat: 0.1 },
  { name: "Maçã", category: "Frutas", kcal: 56, protein: 0.3, carbs: 15.2, fat: 0.2 },
  { name: "Mamão papaia", category: "Frutas", kcal: 40, protein: 0.5, carbs: 10.4, fat: 0.1 },
  { name: "Laranja", category: "Frutas", kcal: 45, protein: 1, carbs: 11.5, fat: 0.2 },
  { name: "Morango", category: "Frutas", kcal: 30, protein: 0.9, carbs: 6.8, fat: 0.3 },
  { name: "Abacate", category: "Frutas", kcal: 96, protein: 1.2, carbs: 6, fat: 8.4 },
  { name: "Manga", category: "Frutas", kcal: 64, protein: 0.5, carbs: 17, fat: 0.3 },
  { name: "Uva", category: "Frutas", kcal: 53, protein: 0.6, carbs: 13.3, fat: 0.2 },
  { name: "Abobrinha refogada", category: "Vegetais", kcal: 19, protein: 1.2, carbs: 4, fat: 0.2 },
  { name: "Brócolis cozido", category: "Vegetais", kcal: 25, protein: 2.1, carbs: 4.4, fat: 0.3 },
  { name: "Couve refogada", category: "Vegetais", kcal: 27, protein: 1.5, carbs: 4.3, fat: 0.7 },
  { name: "Cenoura crua", category: "Vegetais", kcal: 34, protein: 1.3, carbs: 7.7, fat: 0.2 },
  { name: "Tomate", category: "Vegetais", kcal: 15, protein: 1.1, carbs: 3.1, fat: 0.2 },
  { name: "Alface", category: "Vegetais", kcal: 11, protein: 1, carbs: 1.7, fat: 0.2 },
  { name: "Pepino", category: "Vegetais", kcal: 10, protein: 0.7, carbs: 2, fat: 0.1 },
  { name: "Beterraba cozida", category: "Vegetais", kcal: 32, protein: 1.3, carbs: 7.6, fat: 0.1 },
  { name: "Leite desnatado", category: "Laticínios", kcal: 35, protein: 3.4, carbs: 4.9, fat: 0.2 },
  { name: "Leite integral", category: "Laticínios", kcal: 61, protein: 3.2, carbs: 4.7, fat: 3.3 },
  { name: "Iogurte natural desnatado", category: "Laticínios", kcal: 51, protein: 4.1, carbs: 6.8, fat: 0.2 },
  { name: "Queijo minas frescal", category: "Laticínios", kcal: 264, protein: 17.4, carbs: 3.2, fat: 20 },
  { name: "Queijo cottage", category: "Laticínios", kcal: 98, protein: 11, carbs: 3.4, fat: 4.3 },
  { name: "Requeijão light", category: "Laticínios", kcal: 148, protein: 10, carbs: 4, fat: 10 },
  { name: "Whey protein (pó)", category: "Suplementos", kcal: 400, protein: 80, carbs: 8, fat: 6 },
  { name: "Azeite de oliva extravirgem", category: "Óleos e gorduras", kcal: 884, protein: 0, carbs: 0, fat: 100 },
  { name: "Castanha-do-pará", category: "Oleaginosas", kcal: 656, protein: 14.3, carbs: 12.3, fat: 66.4 },
  { name: "Amêndoas", category: "Oleaginosas", kcal: 579, protein: 21.2, carbs: 21.6, fat: 49.9 },
  { name: "Pasta de amendoim integral", category: "Oleaginosas", kcal: 588, protein: 25, carbs: 20, fat: 50 },
];
